In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from scipy import stats

In [2]:
data = pd.read_csv("social_anxiety_dataset.csv")
data.head()

,Age,Gender,Occupation,Sleep Hours,Physical Activity (hrs/week),Caffeine Intake (mg/day),Alcohol Consumption (drinks/week),Smoking,Family History of Anxiety,Stress Level (1-10),...,Sweating Level (1-5),Dizziness,Medication,Therapy Sessions (per month),Recent Major Life Event,Diet Quality (1-10),Anxiety Level (1-10),Target,is_Anxious,Therapy History
0,59.0,Other,Teacher,7.0,2.4,40.0,5,Yes,No,4,...,5,No,No,0,Yes,1.0,2.0,0,0,Group Therapy
1,46.0,Female,Student,5.1,5.4,156.0,11,NaN,No,3,...,4,Yes,No,2,No,1.0,4.0,0,0,NaN
2,40.0,Other,Lawyer,5.1,1.9,570.0,14,Yes,Yes,9,...,3,No,No,6,Yes,4.0,9.0,1,1,NaN
3,40.0,Male,Nurse,7.6,0.9,129.0,0,No,No,9,...,2,No,NaN,2,No,2.0,6.0,0,0,NaN
4,26.0,Male,Other,6.7,3.0,64.0,13,No,No,15,...,4,No,Yes,0,Yes,4.0,3.0,0,0,NaN

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2030 entries, 0 to 2029
Data columns (total 22 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Age                                1968 non-null   float64
 1   Gender                             1911 non-null   object
 2   Occupation                         2030 non-null   object
 3   Sleep Hours                        1994 non-null   float64
 4   Physical Activity (hrs/week)       2030 non-null   float64
 5   Caffeine Intake (mg/day)           1936 non-null   float64
 6   Alcohol Consumption (drinks/week)  2030 non-null   int64
 7   Smoking                            1924 non-null   object
 8   Family History of Anxiety          2030 non-null   object
 9   Stress Level (1-10)                2030 non-null   int64
 10  Heart Rate (bpm)                   2030 non-null   int64
 11  Breathing Rate (breaths/min)       2030 non-null   int64
 12  Sweating Level (1-5)               2030 non-null   int64
 13  Dizziness                          2030 non-null   object
 14  Medication                         1921 non-null   object
 15  Therapy Sessions (per month)       2030 non-null   int64
 16  Recent Major Life Event            2030 non-null   object
 17  Diet Quality (1-10)                1952 non-null   float64
 18  Anxiety Level (1-10)               2030 non-null   float64
 19  Target                             2030 non-null   int64
 20  is_Anxious                         2030 non-null   int64
 21  Therapy History                    203 non-null    object
dtypes: float64(6), int64(8), object(8)
memory usage: 349.0+ KB

In [3]:
data.describe()

,Age,Sleep Hours,Physical Activity (hrs/week),Caffeine Intake (mg/day),Alcohol Consumption (drinks/week),Stress Level (1-10),Heart Rate (bpm),Breathing Rate (breaths/min),Sweating Level (1-5),Therapy Sessions (per month),Diet Quality (1-10),Anxiety Level (1-10),Target,is_Anxious
count,1968.000000,1994.000000,2030.000000,1936.000000,2030.000000,2030.000000,2030.000000,2030.000000,2030.000000,2030.000000,1952.000000,2030.000000,2030.000000,2030.000000
mean,39.921748,6.424624,2.800246,306.275826,9.490148,6.028571,93.066502,20.955665,3.095567,2.359113,5.234119,3.922660,0.103448,0.103448
std,13.243754,2.161544,2.233899,208.012717,6.028653,3.137269,23.313430,5.182524,1.392697,2.148642,2.884946,2.139176,0.304619,0.304619
min,18.000000,-10.000000,-10.000000,0.000000,-10.000000,1.000000,60.000000,12.000000,1.000000,0.000000,1.000000,1.000000,0.000000,0.000000
25%,29.000000,5.800000,1.400000,177.750000,5.000000,3.000000,76.000000,17.000000,2.000000,1.000000,3.000000,2.000000,0.000000,0.000000
50%,40.000000,6.700000,2.800000,277.500000,10.000000,6.000000,93.000000,21.000000,3.000000,2.000000,5.000000,4.000000,0.000000,0.000000
75%,51.000000,7.500000,4.200000,391.000000,15.000000,9.000000,107.000000,26.000000,4.000000,3.000000,8.000000,5.000000,0.000000,0.000000
max,64.000000,11.000000,9.200000,1500.000000,19.000000,15.000000,220.000000,29.000000,5.000000,10.000000,10.000000,10.000000,1.000000,1.000000

In [4]:
numeric_columns = ['Age' ,
                   'Sleep Hours',
                   'Physical Activity (hrs/week)', 
                   'Caffeine Intake (mg/day)' ,
                   'Alcohol Consumption (drinks/week)' ,
                   'Stress Level (1-10)' ,
                   'Heart Rate (bpm)' ,
                   'Breathing Rate (breaths/min)' ,
                   'Sweating Level (1-5)' ,
                   'Therapy Sessions (per month)' ,
                   'Diet Quality (1-10)' ,
                   'Anxiety Level (1-10)' ,
                   'Target',
                   'is_Anxious'
                  ]

In [5]:
categorical_columns = ['Gender',
                       'Occupation',
                       'Smoking',
                       'Family History of Anxiety',
                       'Dizziness',
                       'Medication',
                       'Recent Major Life Event',
                       'Therapy History'
                       ]

# Preprocessing

## Info

In [ ]:
# all participants are adults

### Stress Level (1–10)
A simple self‑rating tool where a person estimates how stressed they feel right now. It’s subjective, but using clear anchors helps keep ratings consistent.

1 – Completely relaxed  
No noticeable stress. Calm, clear thinking, body relaxed.

2 – Very mild tension  
Slight pressure but easily manageable.

3 – Low stress  
Aware of some demands, but still comfortable and functioning well.

4 – Noticeable stress  
You feel somewhat pressured or distracted.

5 – Moderate stress  
Stress is clearly present; concentration takes more effort.

6 – Elevated stress  
Feeling tense or irritable; performance may start to drop.

7 – High stress  
Difficult to focus, physical symptoms may appear (tight shoulders, faster heart rate).

8 – Very high stress  
Overwhelmed; thinking becomes less clear and emotions stronger.

9 – Extreme stress  
Close to panic or shutdown; functioning is very difficult.

10 – Maximum stress / crisis  
Panic, breakdown, or inability to cope.

How people usually measure it:
- Self‑check: “Where am I right now on the 1–10 scale?”
- Body cues: heart rate, muscle tension, breathing, headaches.
- Mental cues: racing thoughts, inability to focus, irritability.
- Behavior cues: avoidance, snapping at people, mistakes.

Many therapists and coaches ask clients to rate stress before and after an activity (meeting, workout, breathing exercise) to see what helps.

---

### Sweating Level (1–5)

1 – None / Dry  
Skin is dry. No noticeable sweating.

2 – Slight  
Very light moisture on skin (forehead, palms, or underarms), but not visible to others.

3 – Moderate  
Clearly noticeable sweat. Skin feels damp; small sweat spots may appear on clothing.

4 – Heavy  
Visible sweating and larger sweat patches on clothing. Sweat may drip or require wiping.

5 – Extreme / Profuse  
Constant dripping or soaking clothing. Sweat runs down face or body.

This type of scale is often used in exercise studies, heat stress monitoring, or medical observations to quickly rate sweating intensity.

---

### Diet Quality (1–10)

1 – Very poor  
Mostly ultra‑processed foods, sugary drinks, fast food, little to no fruits or vegetables.

2 – Poor  
Frequent junk food and refined carbs; very low nutrient variety.

3 – Below average  
Some real food, but still heavy in processed items and added sugars.

4 – Somewhat unhealthy  
Occasional fruits/vegetables but inconsistent balance; many refined foods.

5 – Average  
Mixed diet: some healthy meals, some unhealthy ones.

6 – Fairly good  
Regular fruits/vegetables and home‑cooked meals, but still room for improvement.

7 – Good  
Balanced meals most of the time; decent protein, whole grains, fruits, and vegetables.

8 – Very good  
Mostly whole foods, good nutrient balance, limited processed foods.

9 – Excellent  
Highly balanced diet with plenty of whole foods, healthy fats, lean proteins, fiber.

10 – Optimal  
Consistently nutrient‑dense, varied diet aligned with strong nutrition guidelines (lots of whole foods, minimal processed items).

People often estimate this based on factors like:
- fruit and vegetable intake  
- whole vs processed foods  
- sugar and sugary drink consumption  
- protein quality  
- variety of nutrients  

---

### Difference Between Stress Levels and Anxiety Levels

Stress and anxiety are related but not the same.

Stress
- Usually a response to a specific external pressure (deadline, exam, argument, workload).
- Often temporary and improves when the situation passes.
- More tied to current demands.
- Symptoms: tension, irritability, trouble concentrating, headaches, fatigue.
- Example: feeling stressed because you have a project due tomorrow.

Anxiety
- More about worry, fear, or anticipation of possible threats, sometimes without a clear trigger.
- Can persist even when no immediate stressor exists.
- Often involves excessive worrying about the future.
- Symptoms: constant worry, restlessness, racing thoughts, rapid heartbeat, sleep problems.
- Example: worrying for days that you might fail something even when nothing immediate is happening.

Simple way to think about it
- Stress: pressure from a situation.  
- Anxiety: the internal feeling of fear or worry, sometimes continuing after the stressor is gone.

They often overlap: prolonged stress can lead to anxiety, and anxiety can make normal stress feel much stronger.

---

### Anxiety Level (1–10)

1 – No anxiety  
Calm, relaxed, no worry.

2 – Very mild  
Slight uneasiness but barely noticeable.

3 – Mild  
Occasional worry or nervousness, but it doesn’t affect functioning.

4 – Noticeable  
Anxiety is present and distracting at times.

5 – Moderate  
Frequent worry; concentration takes effort.

6 – Elevated  
Persistent anxious thoughts, some physical symptoms (restlessness, muscle tension).

7 – High  
Difficult to focus; clear physical symptoms like faster heartbeat or shallow breathing.

8 – Very high  
Strong worry, feeling overwhelmed, hard to think clearly.

9 – Severe  
Near panic; racing thoughts, strong physical discomfort.

10 – Extreme / panic level  
Panic attack or feeling completely unable to cope.

People often judge their number using:
- Thoughts: racing worries, fear, rumination  
- Body signals: heart rate, sweating, tension, nausea  
- Functioning: how much anxiety interferes with tasks or decisions.

## Thresholds

High_stress = stress >= 7  
High_anxiety = anxiety >= 7  
Poor_diet = diet_quality <= 3  
Heavy_sweating = sweating >= 4  
these can be used for **binning**

## Illogical entries

**sleep hours** contain illogical entries. \
the same applies to **Physical acitivity**. \
the same applies to **Alcohol Consumption**. \
**stress level** has max more than 10. \
any unmentioned column is fine.

The **Target** and **is_Anxious** columns are replica of each other:

In [ ]:
(data.Target == data['is_Anxious']).all()

## Skewness

In caffeine Intake there is some diff between mean and median more significant than previous columns.

## Duplicated

In [ ]:
def duplicate_indicator(df : DataFrame) -> str:
    dup_num = df.duplicated().sum()
    if dup_num > 0 :
        return f'Dataframe contains {dup_num} duplicated entries'
    else:
        return 'Dataframe contains no duplicated entries'

In [ ]:
duplicate_indicator(data)

## Nan

In [ ]:
def nan_percentage(df : DataFrame) -> DataFrame:
    total_rows = len(df)
    nan_percentage = [(len(df[df[column].isna()]) / total_rows) * 100 for column in df.columns]
    result = DataFrame(nan_percentage, index = df.columns  , columns = ['Nan Percent'])
    return result

In [ ]:
nan_percentage(data)

## Normality

In [ ]:
# caution : this function checks the normality by deleting the nan
def normality_checker(df : DataFrame , alpha : float = 0.05) -> None:
    normal_col = []
    for column in df.select_dtypes(include=['number']).columns:
        if shapiro(df[column] , nan_policy = 'omit')[1] > alpha:
            normal_col.append(column)
    if normal_col:
        print('List of columns with normal distribution:' , normal_col , sep = '\n')
    else:
        print('No columns follow a normal distribution.')

In [ ]:
normality_checker(data)

In [ ]:
data.select_dtypes(include=['number']).corr()