In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from scipy import stats

In [2]:
df = pd.read_csv("social_anxiety_dataset.csv")
df.head()

,Age,Gender,Occupation,Sleep Hours,Physical Activity (hrs/week),Caffeine Intake (mg/day),Alcohol Consumption (drinks/week),Smoking,Family History of Anxiety,Stress Level (1-10),...,Sweating Level (1-5),Dizziness,Medication,Therapy Sessions (per month),Recent Major Life Event,Diet Quality (1-10),Anxiety Level (1-10),Target,is_Anxious,Therapy History
0,59.0,Other,Teacher,7.0,2.4,40.0,5,Yes,No,4,...,5,No,No,0,Yes,1.0,2.0,0,0,Group Therapy
1,46.0,Female,Student,5.1,5.4,156.0,11,NaN,No,3,...,4,Yes,No,2,No,1.0,4.0,0,0,NaN
2,40.0,Other,Lawyer,5.1,1.9,570.0,14,Yes,Yes,9,...,3,No,No,6,Yes,4.0,9.0,1,1,NaN
3,40.0,Male,Nurse,7.6,0.9,129.0,0,No,No,9,...,2,No,NaN,2,No,2.0,6.0,0,0,NaN
4,26.0,Male,Other,6.7,3.0,64.0,13,No,No,15,...,4,No,Yes,0,Yes,4.0,3.0,0,0,NaN

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2030 entries, 0 to 2029
Data columns (total 22 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Age                                1968 non-null   float64
 1   Gender                             1911 non-null   object
 2   Occupation                         2030 non-null   object
 3   Sleep Hours                        1994 non-null   float64
 4   Physical Activity (hrs/week)       2030 non-null   float64
 5   Caffeine Intake (mg/day)           1936 non-null   float64
 6   Alcohol Consumption (drinks/week)  2030 non-null   int64
 7   Smoking                            1924 non-null   object
 8   Family History of Anxiety          2030 non-null   object
 9   Stress Level (1-10)                2030 non-null   int64
 10  Heart Rate (bpm)                   2030 non-null   int64
 11  Breathing Rate (breaths/min)       2030 non-null   int64
 12  Sweating Level (1-5)               2030 non-null   int64
 13  Dizziness                          2030 non-null   object
 14  Medication                         1921 non-null   object
 15  Therapy Sessions (per month)       2030 non-null   int64
 16  Recent Major Life Event            2030 non-null   object
 17  Diet Quality (1-10)                1952 non-null   float64
 18  Anxiety Level (1-10)               2030 non-null   float64
 19  Target                             2030 non-null   int64
 20  is_Anxious                         2030 non-null   int64
 21  Therapy History                    203 non-null    object
dtypes: float64(6), int64(8), object(8)
memory usage: 349.0+ KB

In [3]:
df.describe()

,Age,Sleep Hours,Physical Activity (hrs/week),Caffeine Intake (mg/day),Alcohol Consumption (drinks/week),Stress Level (1-10),Heart Rate (bpm),Breathing Rate (breaths/min),Sweating Level (1-5),Therapy Sessions (per month),Diet Quality (1-10),Anxiety Level (1-10),Target,is_Anxious
count,1968.000000,1994.000000,2030.000000,1936.000000,2030.000000,2030.000000,2030.000000,2030.000000,2030.000000,2030.000000,1952.000000,2030.000000,2030.000000,2030.000000
mean,39.921748,6.424624,2.800246,306.275826,9.490148,6.028571,93.066502,20.955665,3.095567,2.359113,5.234119,3.922660,0.103448,0.103448
std,13.243754,2.161544,2.233899,208.012717,6.028653,3.137269,23.313430,5.182524,1.392697,2.148642,2.884946,2.139176,0.304619,0.304619
min,18.000000,-10.000000,-10.000000,0.000000,-10.000000,1.000000,60.000000,12.000000,1.000000,0.000000,1.000000,1.000000,0.000000,0.000000
25%,29.000000,5.800000,1.400000,177.750000,5.000000,3.000000,76.000000,17.000000,2.000000,1.000000,3.000000,2.000000,0.000000,0.000000
50%,40.000000,6.700000,2.800000,277.500000,10.000000,6.000000,93.000000,21.000000,3.000000,2.000000,5.000000,4.000000,0.000000,0.000000
75%,51.000000,7.500000,4.200000,391.000000,15.000000,9.000000,107.000000,26.000000,4.000000,3.000000,8.000000,5.000000,0.000000,0.000000
max,64.000000,11.000000,9.200000,1500.000000,19.000000,15.000000,220.000000,29.000000,5.000000,10.000000,10.000000,10.000000,1.000000,1.000000

In [4]:
numeric_columns = ['Age' ,
                   'Sleep Hours',
                   'Physical Activity (hrs/week)', 
                   'Caffeine Intake (mg/day)' ,
                   'Alcohol Consumption (drinks/week)' ,
                   'Stress Level (1-10)' ,
                   'Heart Rate (bpm)' ,
                   'Breathing Rate (breaths/min)' ,
                   'Sweating Level (1-5)' ,
                   'Therapy Sessions (per month)' ,
                   'Diet Quality (1-10)' ,
                   'Anxiety Level (1-10)' ,
                   'Target',
                   'is_Anxious'
                  ]

In [5]:
categorical_columns = ['Gender',
                       'Occupation',
                       'Smoking',
                       'Family History of Anxiety',
                       'Dizziness',
                       'Medication',
                       'Recent Major Life Event',
                       'Therapy History'
                       ]